---
- name: Create file and store some date in it 
  hosts: all
  tasks:
    - name: Create a file
      file:
        name: /tmp/file1
        state: touch
    - name: Store some data in the file
      copy:
        content: "IntelliQ"
        dest: /tmp/file1
...
